#!/usr/bin/env bash
# Bash script that installs nginx
sudo apt update
sudo apt install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Hello World!" > /usr/share/nginx/html/index.html
service nginx restart
