#!/usr/bin/env bash
# Bash script that installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Hello World!" > /usr/share/nginx/html/index.html
service nginx restart
