#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy=1.5

sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode: http\n\tdefault_backend nodes\n\n\nbackend nodes\n\tbalance roundrobin\n\tserver 350-web-01 54.160.122.13:80 check\n\tserver 350-web-02 54.145.241.141:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
