#!/usr/bin/env bash
#bash script that displays numbers from 1 to 100
num=1
while [ $num -lt 101 ]; do
	if [ $((num % 5)) == 0 ] && [ $((num % 3)) == 0 ];
	then
		echo "FizzBuzz"
	elif [ $((num % 5)) == 0 ];
	then
		echo "Buzz"
	elif [ $((num % 3)) == 0 ];
	then
		echo "Fizz"
	else
		echo "$num"
	fi
	num=$((num + 1))
done
