#!/usr/bin/env bash
#bash script that gives you information about the school file
exists=0
for file in *; do
	if [ "$file" == "school" ]
	then
		exists=1
		echo "school file exists"
		if [ -s "$file" ]
		then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
		if [ -f "$file" ]
		then
			echo "school is a regular file"
		fi
	fi
done

if [ $exists -eq 0 ]
then
	echo "school file does not exist"
fi
